kind: Pod
apiVersion: v1
metadata:
  name: my-pv-user-pod
spec:
  volumes:
    # This volume is of type persistentVolumeClaim -- i.e.
    # we need a persistent volume.
    - name: a-persistent-volume
      persistentVolumeClaim:
        # Must match claim name from the PVC YAML
        claimName: my-small-pvc
  # Mount the volume into the container and use it
  containers:
    - name: pv-user
      volumeMounts:
      - name: a-persistent-volume
        mountPath: /var/forever
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/forever/file.txt; sleep 5; done"]
